version: 2

project_name: committo

builds:
  - skip: true

archives:
  - id: macos
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Tag }}-macos"
    files:
      - src: dist/committo-macos
        dst: committo
    replacements:
      darwin: macos

  - id: macos-arm64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Tag }}-macos-arm64"
    files:
      - src: dist/committo-macos-arm64
        dst: committo
    replacements:
      darwin: macos

  - id: linux
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Tag }}-linux"
    files:
      - src: dist/committo-linux
        dst: committo

  - id: windows
    format: zip
    name_template: "{{ .ProjectName }}-{{ .Tag }}-windows"
    files:
      - src: dist/committo-windows.exe
        dst: committo.exe

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: committo
    repository:
      owner: dizzyplay
      name: homebrew-committo
      branch: main
      token: "{{ .Env.GH_PAT }}"
    
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    
    homepage: "https://github.com/dizzyplay/committo"
    description: "AI-powered commit message generator that helps developers write better commit messages using LLM"
    license: "MIT"
    
    dependencies:
      - name: git
        type: required
    
    install: |
      bin.install "committo"
    
    test: |
      system "#{bin}/committo", "--help"

release:
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"