name: Release (macOS-arm64)

on:
  push:
    tags: [ "v*" ]          # 예: v0.0.2

permissions:
  contents: write           # 릴리즈 자산 업로드
  pull-requests: write      # Tap PR(또는 직접 push) 용

jobs:
  build-release:
    runs-on: macos-14       # Apple Silicon 러너
    env:
      TAP_REPO: dizzyplay/homebrew-committo
      FORMULA: committo.rb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Build
        run: cargo build --release --target aarch64-apple-darwin

      - name: Package & compute SHA-256
        run: |
          TAG=${GITHUB_REF#refs/tags/}              # v0.0.2
          mkdir dist
          cp target/aarch64-apple-darwin/release/committo dist/
          cd dist
          TARBALL="committo-${TAG}-macos.tar.gz"
          tar -czf "${TARBALL}" committo
          SHA=$(shasum -a 256 "${TARBALL}" | awk '{print $1}')
          echo "ASSET=${TARBALL}" >> $GITHUB_ENV
          echo "SHA256=${SHA}"   >> $GITHUB_ENV

      - name: Create GitHub Release + upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ env.ASSET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Tap formula (direct push)
        env:
          GH_PAT:   ${{ secrets.GH_PAT }}           # PAT( repo:contents, repo:pull_request )
          SHA256:   ${{ env.SHA256 }}
          TAG:      ${{ github.ref_name }}          # v0.0.2
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git clone "https://${GH_PAT}@github.com/${TAP_REPO}.git" tap
          cd tap

          # URL·SHA256 치환
          sed -i '' -E "s|url \".*\"|url \"https://github.com/dizzyplay/committo/releases/download/${TAG}/committo-${TAG}-macos.tar.gz\"|" "${FORMULA}"
          sed -i '' -E "s|sha256 \".*\"|sha256 \"${SHA256}\"|" "${FORMULA}"

          git add "${FORMULA}"
          git commit -m "committo ${TAG} formula update"
          git push origin HEAD:main
